### ISSUE TITLE
Bunch of warnings and error

### ISSUE THREAD

**Issue by codyrotwein** [BlueKai/bluekai-ios-sdk#21]
**When running on iOS 9.2 simulator, I get the following warning:**
Ignoring file /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a, missing required architecture x86_64 in file /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a (3 slices)

**When running on actual device, I get these warnings:**
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: /Users/bgur/Library/Developer/Xcode/DerivedData/Bluekai_SDK-gsznxmoplcvnejeemgvzbzedawoj/Build/Intermediates/PrecompiledHeaders/BlueKai.xcodeproj-Prefix-fkkvvidkxagubiafyekisfbnfyye/BlueKai.xcodeproj-Prefix.pch.pch: No such file or directory
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: /Users/bgur/Library/Developer/Xcode/DerivedData/Bluekai_SDK-gsznxmoplcvnejeemgvzbzedawoj/Build/Intermediates/PrecompiledHeaders/BlueKai.xcodeproj-Prefix-fkkvvidkxagubiafyekisfbnfyye/BlueKai.xcodeproj-Prefix.pch.pch: No object file for requested architecture
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSUndoManager
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSArray
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSDictionary
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSBundle
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSMutableDictionary
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSMutableString
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSMutableArray
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSUserDefaults
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSURL
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSAttributedString
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSURLRequest
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSUUID
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSData
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSError
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSException
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSURLConnection
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSMutableURLRequest
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSURLResponse
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai_Reachability.o):
warning: /Users/bgur/Library/Developer/Xcode/DerivedData/Bluekai_SDK-gsznxmoplcvnejeemgvzbzedawoj/Build/Intermediates/PrecompiledHeaders/BlueKai.xcodeproj-Prefix-dfcquqfyxhevwufvmxeanmiktwsh/BlueKai.xcodeproj-Prefix.pch.pch: No such file or directory
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai_Reachability.o):
warning: /Users/bgur/Library/Developer/Xcode/DerivedData/Bluekai_SDK-gsznxmoplcvnejeemgvzbzedawoj/Build/Intermediates/PrecompiledHeaders/BlueKai.xcodeproj-Prefix-dfcquqfyxhevwufvmxeanmiktwsh/BlueKai.xcodeproj-Prefix.pch.pch: No object file for requested architecture
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai_Reachability.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai_Reachability.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai_Reachability.o):
warning: Could not resolve external type c:objc(cs)NSArray
while processing /Users/codyrotwein/Desktop/Branded/Branded/libBlueKai.a(BlueKai_Reachability.o):
warning: Could not resolve external type c:objc(cs)NSDictionary

**Comment by codyrotwein** [comment]
And error on simulator preventing me from running it:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_BlueKai", referenced from:
      type metadata accessor for __ObjC.BlueKai in AppDelegate.o
ld: symbol(s) not found for architecture x86_64

**Comment by burkaygur** [comment]
Thank you for your feedback @codyrotwein. I just uploaded the 2.0.4 prerelease version. It should solve these issues. Let us know if that works out for you.

https://github.com/BlueKai/bluekai-ios-sdk/blob/master/lib/bluekai-ios-static-ARC-v2.0.4.zip

**Comment by codyrotwein** [comment]
Thanks! It now works on the simulator. However, the simulator and device still have a bunch of those warnings listed above.

**Comment by burkaygur** [comment]
What are the warnings in particular? Could you paste?

**Comment by codyrotwein** [comment]
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: /var/folders/jk/655x2ygx2bb34gc50f_hlmhh0000gn/C/com.apple.DeveloperTools/7.2.1-7C1002/Xcode/7.2.1-7C1002/Xcode/SharedPrecompiledHeaders/BlueKai.xcodeproj-Prefix-anhcbvlbbuldkxeypdidajywrgam/BlueKai.xcodeproj-Prefix.pch.pch: No such file or directory
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: /var/folders/jk/655x2ygx2bb34gc50f_hlmhh0000gn/C/com.apple.DeveloperTools/7.2.1-7C1002/Xcode/7.2.1-7C1002/Xcode/SharedPrecompiledHeaders/BlueKai.xcodeproj-Prefix-anhcbvlbbuldkxeypdidajywrgam/BlueKai.xcodeproj-Prefix.pch.pch: No object file for requested architecture
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSUndoManager
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSArray
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSDictionary
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSBundle
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSMutableDictionary
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSMutableString
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSMutableArray
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSUserDefaults
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSURL
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSAttributedString
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSURLRequest
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSUUID
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSData
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSError
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSException
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSURLConnection
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSMutableURLRequest
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSURLResponse
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai_Reachability.o):
warning: /var/folders/jk/655x2ygx2bb34gc50f_hlmhh0000gn/C/com.apple.DeveloperTools/7.2.1-7C1002/Xcode/7.2.1-7C1002/Xcode/SharedPrecompiledHeaders/BlueKai.xcodeproj-Prefix-gzailevduwlqdtauzsnmzfwpjlnm/BlueKai.xcodeproj-Prefix.pch.pch: No such file or directory
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai_Reachability.o):
warning: /var/folders/jk/655x2ygx2bb34gc50f_hlmhh0000gn/C/com.apple.DeveloperTools/7.2.1-7C1002/Xcode/7.2.1-7C1002/Xcode/SharedPrecompiledHeaders/BlueKai.xcodeproj-Prefix-gzailevduwlqdtauzsnmzfwpjlnm/BlueKai.xcodeproj-Prefix.pch.pch: No object file for requested architecture
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai_Reachability.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai_Reachability.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai_Reachability.o):
warning: Could not resolve external type c:objc(cs)NSArray
while processing /Users/codyrotwein/Desktop/Branded/Branded/BlueKai/libBlueKai.a(BlueKai_Reachability.o):
warning: Could not resolve external type c:objc(cs)NSDictionary

**Comment by burkaygur** [comment]
This is a known issue with XCode 7. I have pushed the same version but a different build. Could you please download that to see if it fixes these errors? Thank you!

**Comment by codyrotwein** [comment]
Warnings are gone!

**Comment by burkaygur** [comment]
Glad to hear that. Closing the issue.
